// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageBuf.proto
package com.lnnk.netty.codec;


public final class MessageBuf {
    private MessageBuf() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface JMTransferOrBuilder extends
            // @@protoc_insertion_point(interface_extends:JMTransfer)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 接口版本号
         * </pre>
         *
         * <code>string version = 1;</code>
         *
         * @return The version.
         */
        java.lang.String getVersion();

        /**
         * <pre>
         * 接口版本号
         * </pre>
         *
         * <code>string version = 1;</code>
         *
         * @return The bytes for version.
         */
        com.google.protobuf.ByteString
        getVersionBytes();

        /**
         * <pre>
         * 设备uuid
         * </pre>
         *
         * <code>string deviceId = 2;</code>
         *
         * @return The deviceId.
         */
        java.lang.String getDeviceId();

        /**
         * <pre>
         * 设备uuid
         * </pre>
         *
         * <code>string deviceId = 2;</code>
         *
         * @return The bytes for deviceId.
         */
        com.google.protobuf.ByteString
        getDeviceIdBytes();

        /**
         * <pre>
         * 内容
         * </pre>
         *
         * <code>string content = 3;</code>
         *
         * @return The content.
         */
        java.lang.String getContent();

        /**
         * <pre>
         * 内容
         * </pre>
         *
         * <code>string content = 3;</code>
         *
         * @return The bytes for content.
         */
        com.google.protobuf.ByteString
        getContentBytes();
    }

    /**
     * <pre>
     * 生成文件命令  protoc ./MessageBuf.proto --java_out=./
     * </pre>
     * <p>
     * Protobuf type {@code JMTransfer}
     */
    public static final class JMTransfer extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:JMTransfer)
            JMTransferOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use JMTransfer.newBuilder() to construct.
        private JMTransfer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private JMTransfer() {
            version_ = "";
            deviceId_ = "";
            content_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new JMTransfer();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private JMTransfer(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            version_ = s;
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            deviceId_ = s;
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            content_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return MessageBuf.internal_static_JMTransfer_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return MessageBuf.internal_static_JMTransfer_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            MessageBuf.JMTransfer.class, MessageBuf.JMTransfer.Builder.class);
        }

        public static final int VERSION_FIELD_NUMBER = 1;
        private volatile java.lang.Object version_;

        /**
         * <pre>
         * 接口版本号
         * </pre>
         *
         * <code>string version = 1;</code>
         *
         * @return The version.
         */
        @java.lang.Override
        public java.lang.String getVersion() {
            java.lang.Object ref = version_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                version_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 接口版本号
         * </pre>
         *
         * <code>string version = 1;</code>
         *
         * @return The bytes for version.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getVersionBytes() {
            java.lang.Object ref = version_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                version_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int DEVICEID_FIELD_NUMBER = 2;
        private volatile java.lang.Object deviceId_;

        /**
         * <pre>
         * 设备uuid
         * </pre>
         *
         * <code>string deviceId = 2;</code>
         *
         * @return The deviceId.
         */
        @java.lang.Override
        public java.lang.String getDeviceId() {
            java.lang.Object ref = deviceId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                deviceId_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 设备uuid
         * </pre>
         *
         * <code>string deviceId = 2;</code>
         *
         * @return The bytes for deviceId.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getDeviceIdBytes() {
            java.lang.Object ref = deviceId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                deviceId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int CONTENT_FIELD_NUMBER = 3;
        private volatile java.lang.Object content_;

        /**
         * <pre>
         * 内容
         * </pre>
         *
         * <code>string content = 3;</code>
         *
         * @return The content.
         */
        @java.lang.Override
        public java.lang.String getContent() {
            java.lang.Object ref = content_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                content_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * 内容
         * </pre>
         *
         * <code>string content = 3;</code>
         *
         * @return The bytes for content.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getContentBytes() {
            java.lang.Object ref = content_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                content_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getVersionBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, version_);
            }
            if (!getDeviceIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceId_);
            }
            if (!getContentBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getVersionBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, version_);
            }
            if (!getDeviceIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceId_);
            }
            if (!getContentBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof MessageBuf.JMTransfer)) {
                return super.equals(obj);
            }
            MessageBuf.JMTransfer other = (MessageBuf.JMTransfer) obj;

            if (!getVersion()
                    .equals(other.getVersion())) return false;
            if (!getDeviceId()
                    .equals(other.getDeviceId())) return false;
            if (!getContent()
                    .equals(other.getContent())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + VERSION_FIELD_NUMBER;
            hash = (53 * hash) + getVersion().hashCode();
            hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
            hash = (53 * hash) + getDeviceId().hashCode();
            hash = (37 * hash) + CONTENT_FIELD_NUMBER;
            hash = (53 * hash) + getContent().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static MessageBuf.JMTransfer parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MessageBuf.JMTransfer parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MessageBuf.JMTransfer parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MessageBuf.JMTransfer parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MessageBuf.JMTransfer parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MessageBuf.JMTransfer parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MessageBuf.JMTransfer parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static MessageBuf.JMTransfer parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static MessageBuf.JMTransfer parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static MessageBuf.JMTransfer parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static MessageBuf.JMTransfer parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static MessageBuf.JMTransfer parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(MessageBuf.JMTransfer prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 生成文件命令  protoc ./MessageBuf.proto --java_out=./
         * </pre>
         * <p>
         * Protobuf type {@code JMTransfer}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:JMTransfer)
                MessageBuf.JMTransferOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return MessageBuf.internal_static_JMTransfer_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return MessageBuf.internal_static_JMTransfer_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                MessageBuf.JMTransfer.class, MessageBuf.JMTransfer.Builder.class);
            }

            // Construct using MessageBuf.JMTransfer.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                version_ = "";

                deviceId_ = "";

                content_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return MessageBuf.internal_static_JMTransfer_descriptor;
            }

            @java.lang.Override
            public MessageBuf.JMTransfer getDefaultInstanceForType() {
                return MessageBuf.JMTransfer.getDefaultInstance();
            }

            @java.lang.Override
            public MessageBuf.JMTransfer build() {
                MessageBuf.JMTransfer result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public MessageBuf.JMTransfer buildPartial() {
                MessageBuf.JMTransfer result = new MessageBuf.JMTransfer(this);
                result.version_ = version_;
                result.deviceId_ = deviceId_;
                result.content_ = content_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof MessageBuf.JMTransfer) {
                    return mergeFrom((MessageBuf.JMTransfer) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(MessageBuf.JMTransfer other) {
                if (other == MessageBuf.JMTransfer.getDefaultInstance()) return this;
                if (!other.getVersion().isEmpty()) {
                    version_ = other.version_;
                    onChanged();
                }
                if (!other.getDeviceId().isEmpty()) {
                    deviceId_ = other.deviceId_;
                    onChanged();
                }
                if (!other.getContent().isEmpty()) {
                    content_ = other.content_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                MessageBuf.JMTransfer parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (MessageBuf.JMTransfer) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object version_ = "";

            /**
             * <pre>
             * 接口版本号
             * </pre>
             *
             * <code>string version = 1;</code>
             *
             * @return The version.
             */
            public java.lang.String getVersion() {
                java.lang.Object ref = version_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    version_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 接口版本号
             * </pre>
             *
             * <code>string version = 1;</code>
             *
             * @return The bytes for version.
             */
            public com.google.protobuf.ByteString
            getVersionBytes() {
                java.lang.Object ref = version_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    version_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 接口版本号
             * </pre>
             *
             * <code>string version = 1;</code>
             *
             * @param value The version to set.
             * @return This builder for chaining.
             */
            public Builder setVersion(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                version_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 接口版本号
             * </pre>
             *
             * <code>string version = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearVersion() {

                version_ = getDefaultInstance().getVersion();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 接口版本号
             * </pre>
             *
             * <code>string version = 1;</code>
             *
             * @param value The bytes for version to set.
             * @return This builder for chaining.
             */
            public Builder setVersionBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                version_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object deviceId_ = "";

            /**
             * <pre>
             * 设备uuid
             * </pre>
             *
             * <code>string deviceId = 2;</code>
             *
             * @return The deviceId.
             */
            public java.lang.String getDeviceId() {
                java.lang.Object ref = deviceId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    deviceId_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 设备uuid
             * </pre>
             *
             * <code>string deviceId = 2;</code>
             *
             * @return The bytes for deviceId.
             */
            public com.google.protobuf.ByteString
            getDeviceIdBytes() {
                java.lang.Object ref = deviceId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    deviceId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 设备uuid
             * </pre>
             *
             * <code>string deviceId = 2;</code>
             *
             * @param value The deviceId to set.
             * @return This builder for chaining.
             */
            public Builder setDeviceId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                deviceId_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 设备uuid
             * </pre>
             *
             * <code>string deviceId = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearDeviceId() {

                deviceId_ = getDefaultInstance().getDeviceId();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 设备uuid
             * </pre>
             *
             * <code>string deviceId = 2;</code>
             *
             * @param value The bytes for deviceId to set.
             * @return This builder for chaining.
             */
            public Builder setDeviceIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                deviceId_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object content_ = "";

            /**
             * <pre>
             * 内容
             * </pre>
             *
             * <code>string content = 3;</code>
             *
             * @return The content.
             */
            public java.lang.String getContent() {
                java.lang.Object ref = content_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    content_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 内容
             * </pre>
             *
             * <code>string content = 3;</code>
             *
             * @return The bytes for content.
             */
            public com.google.protobuf.ByteString
            getContentBytes() {
                java.lang.Object ref = content_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    content_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 内容
             * </pre>
             *
             * <code>string content = 3;</code>
             *
             * @param value The content to set.
             * @return This builder for chaining.
             */
            public Builder setContent(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                content_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 内容
             * </pre>
             *
             * <code>string content = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearContent() {

                content_ = getDefaultInstance().getContent();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 内容
             * </pre>
             *
             * <code>string content = 3;</code>
             *
             * @param value The bytes for content to set.
             * @return This builder for chaining.
             */
            public Builder setContentBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                content_ = value;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:JMTransfer)
        }

        // @@protoc_insertion_point(class_scope:JMTransfer)
        private static final MessageBuf.JMTransfer DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new MessageBuf.JMTransfer();
        }

        public static MessageBuf.JMTransfer getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<JMTransfer>
                PARSER = new com.google.protobuf.AbstractParser<JMTransfer>() {
            @java.lang.Override
            public JMTransfer parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new JMTransfer(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<JMTransfer> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<JMTransfer> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public MessageBuf.JMTransfer getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_JMTransfer_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_JMTransfer_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\020MessageBuf.proto\"@\n\nJMTransfer\022\017\n\007vers" +
                        "ion\030\001 \001(\t\022\020\n\010deviceId\030\002 \001(\t\022\017\n\007content\030\003" +
                        " \001(\tB\014B\nMessageBufb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_JMTransfer_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_JMTransfer_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_JMTransfer_descriptor,
                new java.lang.String[]{"Version", "DeviceId", "Content",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
